# HISTOGRAMS DEFAULT SIZES
DEFAULT_1D_HISTOGRAM_NBINS = 16
DEFAULT_2D_HISTOGRAM_NBINS = 9
DEFAULT_3D_HISTOGRAM_NBINS = 15

# REFERENCE SAMPLE SIZE FOR CHARACTERISTICS COMPARISON
REFERENCE_SAMPLE_SIZE = 500
